/*
 Navicat Premium Data Transfer

 Source Server         : postgres
 Source Server Type    : PostgreSQL
 Source Server Version : 150001 (150001)
 Source Host           : localhost:5432
 Source Catalog        : crud_node
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 150001 (150001)
 File Encoding         : 65001

 Date: 28/05/2023 12:07:21
*/


-- ----------------------------
-- Sequence structure for epresence_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."epresence_id_seq";
CREATE SEQUENCE "public"."epresence_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;
ALTER SEQUENCE "public"."epresence_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for users_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."users_id_seq";
CREATE SEQUENCE "public"."users_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;
ALTER SEQUENCE "public"."users_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Table structure for epresences
-- ----------------------------
DROP TABLE IF EXISTS "public"."epresences";
CREATE TABLE "public"."epresences" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "id_users" int4,
  "type" varchar(255) COLLATE "pg_catalog"."default",
  "is_approve" bool,
  "waktu" timestamp(6)
)
;
ALTER TABLE "public"."epresences" OWNER TO "postgres";

-- ----------------------------
-- Records of epresences
-- ----------------------------
BEGIN;
INSERT INTO "public"."epresences" ("id", "id_users", "type", "is_approve", "waktu") VALUES (6, 12, 'OUT', 'f', '2023-05-27 21:03:58.937698');
INSERT INTO "public"."epresences" ("id", "id_users", "type", "is_approve", "waktu") VALUES (8, 12, 'OUT', 'f', '2023-05-28 21:04:12.905619');
INSERT INTO "public"."epresences" ("id", "id_users", "type", "is_approve", "waktu") VALUES (7, 12, 'IN', 'f', '2023-05-28 21:04:12.282099');
INSERT INTO "public"."epresences" ("id", "id_users", "type", "is_approve", "waktu") VALUES (5, 12, 'IN', 't', '2023-05-27 21:03:57.323173');
COMMIT;

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS "public"."users";
CREATE TABLE "public"."users" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "nama" varchar(255) COLLATE "pg_catalog"."default",
  "npp" int8,
  "password" varchar(255) COLLATE "pg_catalog"."default",
  "email" varchar(255) COLLATE "pg_catalog"."default",
  "npp_supervisor" int8
)
;
ALTER TABLE "public"."users" OWNER TO "postgres";

-- ----------------------------
-- Records of users
-- ----------------------------
BEGIN;
INSERT INTO "public"."users" ("id", "nama", "npp", "password", "email", "npp_supervisor") VALUES (11, 'Supervisor', 11111, '$2b$10$vLje6nX7GOfGUbqj8w8kYeOajVuQWpfcQjLK9xSDlyP4PtiJk/5Ja', 'spv@email.com', NULL);
INSERT INTO "public"."users" ("id", "nama", "npp", "password", "email", "npp_supervisor") VALUES (12, 'Ananda Bayu', 2222, '$2b$10$IuYw3vgQJ279io8h3BHHUufqv382h2SVU0J.XGpTTONSrzkoxwy6K', 'bayu@email.com', 11111);
COMMIT;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."epresence_id_seq"
OWNED BY "public"."epresences"."id";
SELECT setval('"public"."epresence_id_seq"', 32, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."users_id_seq"
OWNED BY "public"."users"."id";
SELECT setval('"public"."users_id_seq"', 12, true);

-- ----------------------------
-- Auto increment value for epresences
-- ----------------------------
SELECT setval('"public"."epresence_id_seq"', 32, true);

-- ----------------------------
-- Primary Key structure for table epresences
-- ----------------------------
ALTER TABLE "public"."epresences" ADD CONSTRAINT "epresence_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for users
-- ----------------------------
SELECT setval('"public"."users_id_seq"', 12, true);

-- ----------------------------
-- Primary Key structure for table users
-- ----------------------------
ALTER TABLE "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table epresences
-- ----------------------------
ALTER TABLE "public"."epresences" ADD CONSTRAINT "fwadaw" FOREIGN KEY ("id_users") REFERENCES "public"."users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
